"""Add transaction_id to Paiement model

Revision ID: 0f91a1f00952
Revises: 13891d7544f9
Create Date: 2025-07-16 14:54:19.328482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f91a1f00952'
down_revision = '13891d7544f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_paiements_transaction_id', ['transaction_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
