"""update Contrat schema

Revision ID: 13891d7544f9
Revises: a1c5852e2bdb
Create Date: 2025-07-11 23:01:01.989869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13891d7544f9'
down_revision = 'a1c5852e2bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_contrats')
    with op.batch_alter_table('contrats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duree_mois', sa.Integer(), nullable=True))
        batch_op.alter_column('montant_caution',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('mois_caution',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrats', schema=None) as batch_op:
        batch_op.alter_column('mois_caution',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('montant_caution',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.drop_column('duree_mois')

    op.create_table('_alembic_tmp_contrats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('locataire_id', sa.INTEGER(), nullable=False),
    sa.Column('chambre_id', sa.INTEGER(), nullable=False),
    sa.Column('date_debut', sa.DATE(), nullable=False),
    sa.Column('date_fin', sa.DATE(), nullable=False),
    sa.Column('montant_caution', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('mois_caution', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('mode_paiement', sa.VARCHAR(length=255), nullable=False),
    sa.Column('periodicite', sa.VARCHAR(length=255), nullable=False),
    sa.Column('statut', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cree_le', sa.DATETIME(), nullable=True),
    sa.Column('duree_mois', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['chambre_id'], ['chambres.id'], ),
    sa.ForeignKeyConstraint(['locataire_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
