"""Add paydunya fields to Paiement model

Revision ID: 629611b12f44
Revises: 0f91a1f00952
Create Date: 2025-07-16 16:05:21.739343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629611b12f44'
down_revision = '0f91a1f00952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paydunya_invoice_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('paydunya_transaction_id', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_paiements_transaction_id'), type_='unique')
        batch_op.create_unique_constraint('uq_paiements_paydunya_transaction_id', ['paydunya_transaction_id'])
        batch_op.create_unique_constraint('uq_paiements_paydunya_invoice_token', ['paydunya_invoice_token'])
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_paiements_transaction_id'), ['transaction_id'])
        batch_op.drop_column('paydunya_transaction_id')
        batch_op.drop_column('paydunya_invoice_token')

    # ### end Alembic commands ###
