"""Re-initial migration with explicit table names and refined relations

Revision ID: a1c5852e2bdb
Revises: 
Create Date: 2025-07-02 15:29:10.975028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c5852e2bdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_utilisateur', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=128), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('cni', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nom_utilisateur')
    )
    op.create_table('maisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adresse', sa.String(length=200), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nombre_chambres', sa.Integer(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('proprietaire_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proprietaire_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chambres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maison_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('taille', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('meublee', sa.Boolean(), nullable=True),
    sa.Column('salle_de_bain', sa.Boolean(), nullable=True),
    sa.Column('prix', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['maison_id'], ['maisons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locataire_id', sa.Integer(), nullable=False),
    sa.Column('chambre_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('montant_caution', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mois_caution', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mode_paiement', sa.String(length=255), nullable=False),
    sa.Column('periodicite', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.String(length=255), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chambre_id'], ['chambres.id'], ),
    sa.ForeignKeyConstraint(['locataire_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chambre_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chambre_id'], ['chambres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rendez_vous',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locataire_id', sa.Integer(), nullable=False),
    sa.Column('chambre_id', sa.Integer(), nullable=False),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(length=255), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chambre_id'], ['chambres.id'], ),
    sa.ForeignKeyConstraint(['locataire_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=False),
    sa.Column('date_paiement', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=255), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=False),
    sa.Column('signale_par', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('responsable', sa.String(length=255), nullable=True),
    sa.Column('resolu', sa.Boolean(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ),
    sa.ForeignKeyConstraint(['signale_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problemes')
    op.drop_table('paiements')
    op.drop_table('rendez_vous')
    op.drop_table('medias')
    op.drop_table('contrats')
    op.drop_table('chambres')
    op.drop_table('maisons')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
